import { Toaster } from '@/components/ui/sonner';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { initDb } from '../lib/init-db';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await initDb();

  return (
    <html lang='en'>
      <body className={inter.className}>
        <main>{children}</main>
        <Toaster richColors theme={'light'}/>
      </body>
    </html>
  );
}
